name: Hugo test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_for_build_our_cv:
    timeout-minutes: 10
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

#    - name: install Hugo
#      run: brew install hugo

    - name: Run build
      run: |
        chmod +x build.sh
        . ./build.sh
