name: Hugo test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_for_build_our_cv:
    timeout-minutes: 10
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run build
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        brew install hugo
        mkdir hugoServer
        cd hugoServer
        hugo new site mycv
        cd mycv/themes
        git clone https://gitlab.com/mertbakir/resume-a4.git
        cd resume-a4
        cp config.yaml ../../
        cp -r exampleSite/data ../../
        cd ../../
        rm config.toml
        hugo -D
